#Configuração da api-key
spring.ai.google.genai.api-key=

#Modelo padrão
spring.ai.google.genai.chat.options.model=gemini-2.5-flash

# Opcional: logging pra ver chamadas
logging.level.org.springframework.ai=DEBUG
logging.level.com.google=DEBUG